USE [master]
GO

/****** Object:  Database [Exam]    Script Date: 22.10.2022 21:34:05 ******/
CREATE DATABASE [Exam]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Exam', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Exam.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 81920KB )
 LOG ON 
( NAME = N'Exam_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Exam_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 81920KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Exam].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Exam] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Exam] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Exam] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Exam] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Exam] SET ARITHABORT OFF 
GO

ALTER DATABASE [Exam] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Exam] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Exam] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Exam] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Exam] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Exam] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Exam] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Exam] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Exam] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Exam] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Exam] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Exam] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Exam] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Exam] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Exam] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Exam] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Exam] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Exam] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Exam] SET  MULTI_USER 
GO

ALTER DATABASE [Exam] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Exam] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Exam] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Exam] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Exam] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Exam] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Exam] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Exam] SET  READ_WRITE 
GO

